### ISSUE TITLE
Initialization fails

### ISSUE THREAD

**Issue by bestouff** [vilcans/ld45#1]
Debian 10, rust 1.39:
```
     Running `target/debug/ld45`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: core::option::Option<T>::unwrap
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/macros.rs:12
  16: winit::platform::platform::wayland::window::Window::get_current_monitor
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.3/src/platform/linux/wayland/window.rs:289
  17: winit::platform::platform::Window::get_current_monitor
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.3/src/platform/linux/mod.rs:357
  18: winit::window::<impl winit::Window>::get_current_monitor
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.3/src/window.rs:412
  19: ggez::graphics::context::GraphicsContextGeneric<B>::set_window_mode
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/graphics/context.rs:537
  20: ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>::new
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/graphics/context.rs:301
  21: ggez::context::Context::from_conf
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/context.rs:88
  22: ggez::context::ContextBuilder::build
             at /home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/context.rs:304
  23: ld45::main
             at src/main.rs:664
  24: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  27: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  28: std::panicking::try
             at src/libstd/panicking.rs:271
  29: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  30: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  31: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  32: main
  33: __libc_start_main
  34: _start
```
The line failing is this one:
```rust
    let (ctx, event_loop) = &mut builder.build()?;
```

**Comment by vilcans** [comment]
It compiles just fine. That's a runtime error. For some reason it fails in the function `winit::platform::platform::wayland::window::Window::get_current_monitor`. Do you get the same error if you download the binary from [here](https://ldjam.com/events/ludum-dare/45/legally-dead) and run it?

**Comment by bestouff** [comment]
Yes sorry for the brainfart, I've fixed the title.  
Running your precompiled binary also fails:
```
RUST_BACKTRACE=1 ./ld45 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: winit::platform::platform::wayland::window::Window::get_current_monitor
  12: ggez::graphics::context::GraphicsContextGeneric<B>::set_window_mode
  13: ggez::graphics::context::GraphicsContextGeneric<ggez::graphics::GlBackendSpec>::new
  14: ggez::context::ContextBuilder::build
  15: ld45::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: std::panicking::try
             at src/libstd/panicking.rs:275
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by vilcans** [comment]
Do you know if any other game made with ggez works?

Try replacing main.rs with this (based on [Basic Project Template](https://docs.rs/ggez/0.5.1/ggez/)). It should open an empty window. Do you still get an error?

```
use ggez::{Context, ContextBuilder, GameResult};
use ggez::event::{self, EventHandler};
use ggez::graphics;

fn main() {
    // Make a Context and an EventLoop.
    let (mut ctx, mut event_loop) =
       ContextBuilder::new("game_name", "author_name")
           .build()
           .unwrap();

    // Create an instance of your event handler.
    // Usually, you should provide it with the Context object
    // so it can load resources like images during setup.
    let mut my_game = MyGame::new(&mut ctx);

    // Run!
    match event::run(&mut ctx, &mut event_loop, &mut my_game) {
        Ok(_) => println!("Exited cleanly."),
        Err(e) => println!("Error occured: {}", e)
    }
}

struct MyGame {
    // Your state here...
}

impl MyGame {
    pub fn new(_ctx: &mut Context) -> MyGame {
        // Load/create resources here: images, fonts, sounds, etc.
        MyGame { }
    }
}

impl EventHandler for MyGame {
    fn update(&mut self, _ctx: &mut Context) -> GameResult<()> {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
        graphics::clear(ctx, graphics::WHITE);

        // Draw code here...

        graphics::present(ctx)
    }
}
```

**Comment by bestouff** [comment]
No you're right, even `cargo run --example 01_super_simple` from `ggez` fails.  
I guess I'll have to report it there then.

**Comment by bestouff** [comment]
FWIW the bug is ggez/ggez#579
